from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox'])
 page=b.new_page(viewport={'width':390,'height':844})
 page.on('dialog', lambda dialog: dialog.accept())
 errors=[]
 page.on('pageerror',lambda error: errors.append(str(error)))
 import os
 page.goto(os.environ.get('SIGIN_TEST_URL','http://127.0.0.1:4173/'))
 page.get_by_role('button',name='Explorar como estudiante').click()
 page.get_by_role('button',name='Continuar con la semana 1').click()
 page.get_by_role('button',name='Comenzar práctica').click()
 for text in ['Definir producto, período y decisión que debe apoyar','“Producto A: 12 unidades disponibles al cierre de ayer; ventas previstas hoy: 30”','Tiempo para responder la decisión con datos verificados']:
  page.get_by_label(text,exact=True).check()
  page.get_by_role('button',name='Comprobar respuesta').click()
  page.get_by_role('button',name='Revisar antes de terminar' if 'Tiempo' in text else 'Siguiente',exact=True).click()
 page.get_by_role('button',name='Confirmar y terminar').click()
 assert page.locator('.result').inner_text().startswith('10.0')
 assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
 page.get_by_role('button',name='Volver a mi materia').click()
 page.get_by_role('button',name='Continuar con la semana 1').click()
 page.get_by_role('button',name='Comenzar evaluación').click()
 page.get_by_label('Definir producto, período y decisión que debe apoyar',exact=True).check()
 page.get_by_role('button',name='Siguiente',exact=True).click()
 page.get_by_role('button',name='Guardar y volver',exact=False).click()
 # Confirmation is handled by an automatic dialog listener below.
 page.get_by_role('button',name='Comenzar evaluación').click()
 assert page.get_by_label('Definir producto, período y decisión que debe apoyar',exact=True).is_checked()
 page.get_by_role('button',name='Siguiente',exact=True).click()
 page.get_by_label('“Producto A: 12 unidades disponibles al cierre de ayer; ventas previstas hoy: 30”',exact=True).check()
 page.get_by_role('button',name='Siguiente',exact=True).click()
 page.get_by_label('Tiempo para responder la decisión con datos verificados',exact=True).check()
 page.get_by_role('button',name='Revisar antes de terminar',exact=True).click()
 page.get_by_role('button',name='Confirmar y terminar').click()
 assert page.locator('.result').inner_text().startswith('10.0')
 page.get_by_role('button',name='Salir',exact=True).click()
 page.get_by_role('button',name='Explorar panel docente').click()
 page.get_by_role('button',name='Estudiantes',exact=True).click()
 with page.expect_download() as download:
  page.get_by_role('button',name='Descargar plantilla Excel').click()
 path=download.value.path()
 page.locator('#import').set_input_files(path)
 page.get_by_role('button',name='Confirmar filas válidas').wait_for()
 page.get_by_role('button',name='Confirmar filas válidas').click()
 assert page.get_by_role('heading',name='Estudiantes de la materia (2)').is_visible()
 page.screenshot(path='/tmp/sigin-mobile.png',full_page=True)
 page.set_viewport_size({'width':1440,'height':900})
 page.get_by_role('button',name='Semanas',exact=True).click()
 page.screenshot(path='/tmp/sigin-desktop.png',full_page=True)
 assert not errors,errors
 print('PASS browser: practice, score, mobile overflow, Excel template roundtrip, admin navigation; no JavaScript errors')
 b.close()
